import { Router } from 'express';
import { body, validationResult } from 'express-validator';
import { googleLogin, login, me, register } from '../controllers/authController.js';
import { protect } from '../middleware/auth.js';
const router = Router();
const validate = (req, res, next) => { const errors = validationResult(req); if (!errors.isEmpty()) return res.status(400).json({ message: errors.array()[0].msg }); next(); };
router.post('/register', [body('name').trim().isLength({ min: 2 }).withMessage('Name must be at least 2 characters'), body('email').isEmail().withMessage('Enter a valid email'), body('password').isLength({ min: 6 }).withMessage('Password must be at least 6 characters'), validate], register);
router.post('/login', [body('email').isEmail().withMessage('Enter a valid email'), body('password').notEmpty().withMessage('Password is required'), validate], login);
router.post('/google', [body('credential').notEmpty().withMessage('Google credential is required'), validate], googleLogin);
router.get('/me', protect, me);
export default router;
