import 'express-async-errors';
import dotenv from 'dotenv'; dotenv.config();
import express from 'express'; import cors from 'cors'; import morgan from 'morgan';
import { connectDB } from './config/db.js';
import authRoutes from './routes/auth.js'; import productRoutes from './routes/products.js'; import orderRoutes from './routes/orders.js'; import userRoutes from './routes/users.js';
import { notFound, errorHandler } from './middleware/error.js';
const app = express();
app.use(cors({ origin: process.env.CLIENT_URL || 'http://localhost:5173' })); app.use(express.json()); app.use(morgan('dev'));
app.get('/api/health', (req, res) => res.json({ status: 'ok', service: 'shopsphere-api' }));
app.use('/api/auth', authRoutes); app.use('/api/products', productRoutes); app.use('/api/orders', orderRoutes); app.use('/api/users', userRoutes);
app.use(notFound); app.use(errorHandler);
const port = process.env.PORT || 5000;
if (process.env.NODE_ENV !== 'test') connectDB().then(() => app.listen(port, () => console.log(`ShopSphere API running on ${port}`))).catch(error => { console.error(error.message); process.exit(1); });
export default app;
